config/routes.rb
Rails.application.routes.draw do
  resources :laps
  resources :races
  resources :circuits
  resources :pilot_teams
  resources :championships
  resources :pilots
  resources :teams
  resources :brands
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "championships#index"
end

app/models/lap.rb
class Lap < ApplicationRecord
  belongs_to :race
  belongs_to :pilot
end

app/controllers/laps_controller.rb
class LapsController < ApplicationController
  before_action :set_lap, only: %i[ show edit update destroy ]

  # GET /laps or /laps.json
  def index
    @laps = Lap.all
  end

  # GET /laps/1 or /laps/1.json
  def show
  end

  # GET /laps/new
  def new
    @lap = Lap.new
  end

  # GET /laps/1/edit
  def edit
  end

  # POST /laps or /laps.json
  def create
    @lap = Lap.new(lap_params)

    respond_to do |format|
      if @lap.save
        format.html { redirect_to @lap, notice: "Lap was successfully created." }
        format.json { render :show, status: :created, location: @lap }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /laps/1 or /laps/1.json
  def update
    respond_to do |format|
      if @lap.update(lap_params)
        format.html { redirect_to @lap, notice: "Lap was successfully updated." }
        format.json { render :show, status: :ok, location: @lap }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laps/1 or /laps/1.json
  def destroy
    @lap.destroy
    respond_to do |format|
      format.html { redirect_to laps_url, notice: "Lap was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lap
      @lap = Lap.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lap_params
      params.require(:lap).permit(:lap_number, :position, :time, :race_id, :pilot_id)
    end
end

app/helpers/laps_helper.rb
module LapsHelper
end

app/views/laps/_form.html.erb
<%= form_with(model: lap) do |form| %>
  <% if lap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lap.errors.count, "error") %> prohibited this lap from being saved:</h2>

      <ul>
        <% lap.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lap_number %>
    <%= form.number_field :lap_number %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.time_select :time %>
  </div>

  <div class="field">
    <%= form.label :race_id %>
    <%= collection_select(:lap, :race_id, Race.all, :id, :name )  %>
  </div>

  <div class="field">
    <%= form.label :pilot_id %>
    <%= collection_select(:lap, :pilot_id, Pilot.all, :id, :full_name )  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/laps/edit.html.erb
<h1>Editing Lap</h1>

<%= render 'form', lap: @lap %>

<%= link_to 'Show', @lap %> |
<%= link_to 'Back', laps_path %>

app/views/laps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Laps</h1>

<table class="table table-striped" style="background-color:#42F1BD;">
  <thead>
    <tr>
      <th>Lap number</th>
      <th>Position</th>
      <th>Time</th>
      <th>Race</th>
      <th>Pilot</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @laps.each do |lap| %>
      <tr>
        <td><%= lap.lap_number %></td>
        <td><%= lap.position %></td>
        <td><%= lap.time %></td>
        <td><%= lap.race_id %></td>
        <td><%= lap.pilot_id %></td>
        <td><%= link_to 'Show', lap %></td>
        <td><%= link_to 'Edit', edit_lap_path(lap) %></td>
        <td><%= link_to 'Destroy', lap, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lap', new_lap_path %>

app/views/laps/new.html.erb
<h1>New Lap</h1>

<%= render 'form', lap: @lap %>

<%= link_to 'Back', laps_path %>

app/views/laps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lap number:</strong>
  <%= @lap.lap_number %>
</p>

<p>
  <strong>Position:</strong>
  <%= @lap.position %>
</p>

<p>
  <strong>Time:</strong>
  <%= @lap.time %>
</p>

<p>
  <strong>Race:</strong>
  <%= @lap.race_id %>
</p>

<p>
  <strong>Pilot:</strong>
  <%= @lap.pilot_id %>
</p>

<%= link_to 'Edit', edit_lap_path(@lap) %> |
<%= link_to 'Back', laps_path %>