config/routes.rb
Rails.application.routes.draw do
  resources :laps
  resources :races
  resources :circuits
  resources :pilot_teams
  resources :championships
  resources :pilots
  resources :teams
  resources :brands
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "championships#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in

    unless user.id.nil?
      can :manage, :all

    else
      can :manage, Brand, user_id: user.id
      can :create, User
      can :read, User, :id => user.id
      can :update, User, :id => user.id
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :bramds
end

app/models/championship.rb
class Championship < ApplicationRecord
  has_many :pilot_teams
  has_many :races

  def racepoint
    #si en una carrera en la vuelta 35
    if self.race.lap_number == 35 && self.race.position == 1
      puts "*** El ganador de la carrera es: ( #{pilot_team.pilot.full_name}) *** "
    end

    def puntaje (posicion)
      #si en una carrera en la vuelta 35
      if self.race.position == 1
        return = 32
      else self.race.position == 2
          return = 21
        else self.race.position == 3
            return = 16
          else self.race.position == 4
              return = 12
            else self.race.position == 5
                return = 8
              else self.race.position == 6
                  return = 6
                else self.race.position == 7
                    return = 4
                  else self.race.position == 8
                      return = 3
                    else self.race.position == 9
                        return = 2
                      else self.race.position == 10
                          return = 1
      end


  end


end

app/models/circuit.rb
class Circuit < ApplicationRecord
  has_many :races
end

app/models/lap.rb
class Lap < ApplicationRecord
  belongs_to :race
  belongs_to :pilot
end

app/models/pilot.rb
class Pilot < ApplicationRecord
  has_many :pilot_teams
  has_many :laps

  def full_name
      first_name + " " + last_name
    end

end

app/models/pilot_team.rb
class PilotTeam < ApplicationRecord
  belongs_to :team
  belongs_to :pilot
  belongs_to :championship
end

app/models/race.rb
class Race < ApplicationRecord
  belongs_to :circuit
  belongs_to :championship
  has_many :laps
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :brand
    has_many :pilot_teams
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/laps_controller.rb
class LapsController < ApplicationController
  before_action :set_lap, only: %i[ show edit update destroy ]

  # GET /laps or /laps.json
  def index
    @laps = Lap.all
  end

  # GET /laps/1 or /laps/1.json
  def show
  end

  # GET /laps/new
  def new
    @lap = Lap.new
  end

  # GET /laps/1/edit
  def edit
  end

  # POST /laps or /laps.json
  def create
    @lap = Lap.new(lap_params)

    respond_to do |format|
      if @lap.save
        format.html { redirect_to @lap, notice: "Lap was successfully created." }
        format.json { render :show, status: :created, location: @lap }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /laps/1 or /laps/1.json
  def update
    respond_to do |format|
      if @lap.update(lap_params)
        format.html { redirect_to @lap, notice: "Lap was successfully updated." }
        format.json { render :show, status: :ok, location: @lap }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laps/1 or /laps/1.json
  def destroy
    @lap.destroy
    respond_to do |format|
      format.html { redirect_to laps_url, notice: "Lap was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lap
      @lap = Lap.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lap_params
      params.require(:lap).permit(:lap_number, :position, :time, :race_id, :pilot_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/circuits_helper.rb
module CircuitsHelper
end

app/helpers/laps_helper.rb
module LapsHelper
end

app/helpers/pilot_teams_helper.rb
module PilotTeamsHelper
end

app/helpers/pilots_helper.rb
module PilotsHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-xl navbar" style="background-color: #42F1BD;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">TC 2000</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarLight" aria-controls="navbarLight"  aria-expanded="false" aria-label="Toggle navigation"  >
      <span class="navbar-toggler-icon" ></span>
    </button>
    <div class="collapse navbar-collapse show" id="navbarLight">
      <ul class="navbar-nav me-auto mb-2 mb-xl-0">
        <li class="nav-item">
          <%= link_to "Campeonato", championships_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Carrera", races_path, class: 'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to "Circuito", circuits_path, class: 'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to "Vuelta", laps_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Piloto", pilots_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Equipo", teams_path, class: 'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to "Piloto-Equipo", pilot_teams_path, class: 'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to "Marca", brands_path, class: 'nav-link' %>
        </li>
      </ul>

      <%= render 'layouts/user' %>

    </div>
  </div>
</nav>

app/views/layouts/_user.html.erb
<div class="collapse navbar-collapse show" id="navbarWithDropdown">
   <ul class="navbar-nav">
     <% if user_signed_in? %>
       <li class="nav-item dropdown">
         <a class="nav-link dropdown-toggle btn btn-outline-light" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           <span style="color:gray"><%= current_user.email %></span>
         </a>
         <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
           <li><%= link_to "Editar Perfil", edit_user_registration_path, class: "btn" %></li>
           <hr>
           <li><%= link_to "Cerrar Sesión", destroy_user_session_path, class: "btn",  method: :delete  %></li>
         </ul>
       </li>
     <% end %>
   </ul>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finalmoreno</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color:#c6faeb;">
  <%= render :partial => 'layouts/menu' %>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <%= yield %>
  </body>
</html>